// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHBp4i0khJjKpAnzwv501HuAPf7w-l4Ts',
    appId: '1:998986960312:web:06e0e122a7a814328f934d',
    messagingSenderId: '998986960312',
    projectId: 'ddnc-60fd1',
    authDomain: 'ddnc-60fd1.firebaseapp.com',
    storageBucket: 'ddnc-60fd1.appspot.com',
    measurementId: 'G-2BNFZPLTBH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhFoCdwsb8gIoQMLaWWJXeeYDA1FKC0J8',
    appId: '1:998986960312:android:bd864d64e09d49d38f934d',
    messagingSenderId: '998986960312',
    projectId: 'ddnc-60fd1',
    storageBucket: 'ddnc-60fd1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCo6fMIh4TamLPVIdOmuFIsXg4KZsnlIRg',
    appId: '1:998986960312:ios:c5f1f923e50bf1548f934d',
    messagingSenderId: '998986960312',
    projectId: 'ddnc-60fd1',
    storageBucket: 'ddnc-60fd1.appspot.com',
    iosClientId: '998986960312-ssgvv70vf7s51fft7nnpf2ajgiu06f0v.apps.googleusercontent.com',
    iosBundleId: 'com.example.tuan2',
  );
}
